,
'wcf.bookmark.add':							'{lang}wcf.bookmark.add{/lang}',
'wcf.bookmark.add.success':					'{lang}wcf.bookmark.add.success{/lang}',
'wcf.bookmark.edit':						'{lang}wcf.bookmark.edit{/lang}',
'wcf.bookmark.edit.delete':					'{lang}wcf.bookmark.edit.delete{/lang}',
'wcf.bookmark.edit.delete.confirm':			'{lang}wcf.bookmark.edit.delete.confirm{/lang}',
'wcf.bookmark.edit.edit':					'{lang}wcf.bookmark.edit.edit{/lang}',
'wcf.bookmark.edit.share':					'{lang}wcf.bookmark.edit.share{/lang}',
'wcf.bookmark.panel.shared':				'{lang}wcf.bookmark.panel.shared{/lang}',
'wcf.bookmark.panel.showAll':				'{lang}wcf.bookmark.panel.showAll{/lang}',
'wcf.bookmark.profile.moreItems':			'{lang}wcf.bookmark.profile.moreItems{/lang}',
'wcf.bookmark.profile.noMoreItems':			'{lang}wcf.bookmark.profile.noMoreItems{/lang}',
'wcf.bookmark.share.receiver':				'{lang}wcf.bookmark.share.receiver{/lang}',
'wcf.bookmark.share.receiver.description':	'{lang}wcf.bookmark.share.receiver.description{/lang}',
'wcf.bookmark.share.success':				'{lang}wcf.bookmark.share.success{/lang}',
'wcf.bookmark.share.title':					'{lang}wcf.bookmark.share.title{/lang}',
'wcf.bookmark.title.error.tooLong':			'{lang}wcf.bookmark.title.error.tooLong{/lang}',
'wcf.bookmark.url.error.invalid':			'{lang}wcf.bookmark.url.error.invalid{/lang}'
